// 游戏数据定义
const POINT_UPGRADE_CAPS = { count: 10, cooldown: 10, double: 2 };

/**
 * 资源点升级费用：
 * - 采集 / 恢复 / 精炼：只消耗本资源
 * - 精炼重置：自身加工品 + 同档其他资源
 * @param {{ resource: string, processed: string, others?: string[], scale?: number }} cfg
 */
function makePointUpgradeCosts(cfg) {
  const { resource, processed, others = [], scale = 1 } = cfg;
  const amt = (n) => Math.max(1, Math.round(n * scale));
  const self = (n) => ({ [resource]: amt(n) });
  const a = others[0];
  const b = others[1] || others[0];
  const mixed = (p, x, y) => {
    const cost = { [processed]: amt(p) };
    if (x > 0 && a) cost[a] = amt(x);
    if (y > 0 && b) cost[b] = amt(y);
    return cost;
  };
  return {
    count: [
      self(4), self(6), self(9), self(12), self(16),
      self(22), self(30), self(40), self(55), self(75),
    ],
    cooldown: [
      self(8), self(12), self(17), self(24), self(33),
      self(45), self(62), self(85), self(115), self(155),
    ],
    double: [self(28), self(48)],
    /** 精炼重置一次性费用（多种资源） */
    prestige: mixed(20, 28, 22),
  };
}

const GAME_DATA = {
  resources: {
    wood: { id: 'wood', name: '木头', icon: '🪵', color: '#8B6914' },
    plank: { id: 'plank', name: '木板', icon: '🟫', color: '#C4A35A' },
    stone: { id: 'stone', name: '石头', icon: '🪨', color: '#888' },
    stone_slab: { id: 'stone_slab', name: '石板', icon: '▦', color: '#707070' },
    clay: { id: 'clay', name: '黏土', icon: '🟠', color: '#B56A3C' },
    brick: { id: 'brick', name: '砖', icon: '🧱', color: '#A0522D' },
    gravel: { id: 'gravel', name: '砂砾', icon: '🏜️', color: '#C2B280' },
    glass: { id: 'glass', name: '玻璃', icon: '🪟', color: '#A8D8FF' },
    resin: { id: 'resin', name: '树脂', icon: '🍯', color: '#B8860B' },
    pitch: { id: 'pitch', name: '松香', icon: '🟤', color: '#8B4513' },
    copper_ore: { id: 'copper_ore', name: '铜矿', icon: '🟤', color: '#B87333' },
    copper_ingot: { id: 'copper_ingot', name: '铜锭', icon: '🔶', color: '#DA8A67' },
    tin_ore: { id: 'tin_ore', name: '锡矿', icon: '🪙', color: '#A8B4C0' },
    bronze: { id: 'bronze', name: '青铜', icon: '🥉', color: '#CD7F32' },
    zinc_ore: { id: 'zinc_ore', name: '锌矿', icon: '🔘', color: '#9AA5B0' },
    brass: { id: 'brass', name: '黄铜', icon: '🟡', color: '#B5A642' },
    limestone: { id: 'limestone', name: '石灰石', icon: '▫️', color: '#E8E0D0' },
    lime: { id: 'lime', name: '石灰', icon: '⬜', color: '#F5F5DC' },
    coal: { id: 'coal', name: '煤炭', icon: '⚫', color: '#333' },
    coke: { id: 'coke', name: '焦炭', icon: '⬛', color: '#2A2A2A' },
    iron_ore: { id: 'iron_ore', name: '铁矿', icon: '⬛', color: '#555' },
    iron_ingot: { id: 'iron_ingot', name: '铁锭', icon: '⬜', color: '#AAA' },
    steel: { id: 'steel', name: '钢', icon: '🔩', color: '#6B7B8C' },
    silver_ore: { id: 'silver_ore', name: '银矿', icon: '🔹', color: '#C0C0C0' },
    silver_ingot: { id: 'silver_ingot', name: '银锭', icon: 'ミラー', color: '#E8E8E8' },
    sulfur: { id: 'sulfur', name: '硫磺', icon: '🟡', color: '#E6D600' },
    gunpowder: { id: 'gunpowder', name: '火药', icon: '💥', color: '#4A4A4A' },
    obsidian: { id: 'obsidian', name: '黑曜石', icon: '🖤', color: '#1a1a1a' },
    gold_ore: { id: 'gold_ore', name: '金矿', icon: '🟨', color: '#DAA520' },
    gold_ingot: { id: 'gold_ingot', name: '金锭', icon: '🥇', color: '#FFD700' },
    crystal: { id: 'crystal', name: '水晶', icon: '💎', color: '#7FDBFF' },
    polished_crystal: { id: 'polished_crystal', name: '抛光水晶', icon: '💠', color: '#B0E0FF' },
    meteorite: { id: 'meteorite', name: '陨石', icon: '☄️', color: '#4B0082' },
    star_metal: { id: 'star_metal', name: '陨铁', icon: '🌟', color: '#6A5ACD' },
    gear: { id: 'gear', name: '齿轮', icon: '⚙️', color: '#777' },
    food: { id: 'food', name: '食物', icon: '🍖', color: '#C75B39' },
  },

  /**
   * 资源点计数档位（baseMaxCount）：
   * 入门 — 森林 15
   * 低级 — 采石场 / 黏土坑 / 砂砾滩 / 松脂林 ≤24
   * 中级 — 煤矿 / 铜矿 / 锡矿 / 石灰岩场 / 锌矿 ≤45
   * 高级 — 铁矿 / 银矿 / 硫气孔 / 黑曜岩 ＜80
   * 终极 — 金矿 / 水晶洞 / 陨石坑 ≈130
   */
  resourcePoints: {
    berry_bush: {
      id: 'berry_bush',
      name: '浆果丛',
      icon: '🫐',
      description: '采集浆果作为食物。白天由 4 名村民自动采集，约等于 10 人一天的口粮（夜间 22:00–06:00 休息）',
      resource: 'food',
      baseYield: 1,
      baseMaxCount: 12,
      baseCooldown: 0,
      maxUpgrades: { count: 0, cooldown: 0, double: 0 },
      upgradeCosts: { count: [], cooldown: [], double: [] },
      unlockRequires: null,
      isFoodPoint: true,
    },
    forest: {
      id: 'forest',
      name: '森林',
      icon: '🌲',
      description: '砍伐树木获取木头，采集后需等待冷却',
      resource: 'wood',
      baseYield: 1,
      baseMaxCount: 15,
      baseCooldown: 2000,
      maxUpgrades: { ...POINT_UPGRADE_CAPS },
      upgradeCosts: makePointUpgradeCosts({ resource: 'wood', processed: 'plank', others: ['stone_slab', 'resin'] }),
      unlockRequires: null,
    },
    quarry: {
      id: 'quarry',
      name: '采石场',
      icon: '⛏️',
      description: '开采石头（低级）。配上石镐会轻松许多',
      resource: 'stone',
      baseYield: 1,
      tier: 'low',
      baseMaxCount: 24,
      baseCooldown: 2000,
      maxUpgrades: { ...POINT_UPGRADE_CAPS },
      upgradeCosts: makePointUpgradeCosts({ resource: 'stone', processed: 'stone_slab', others: ['clay', 'brick'] }),
      unlockRequires: 'unlock_quarry',
    },
    clay_pit: {
      id: 'clay_pit',
      name: '黏土坑',
      icon: '🟠',
      description: '挖掘黏土（低级）。配上木铲会轻松许多',
      resource: 'clay',
      baseYield: 1,
      tier: 'low',
      baseMaxCount: 24,
      baseCooldown: 2200,
      maxUpgrades: { ...POINT_UPGRADE_CAPS },
      upgradeCosts: makePointUpgradeCosts({ resource: 'clay', processed: 'brick', others: ['stone_slab', 'gravel'] }),
      unlockRequires: 'unlock_clay_pit',
    },
    copper_mine: {
      id: 'copper_mine',
      name: '铜矿',
      icon: '🏔️',
      description: '开采铜矿石（中级）。石镐偏慢，建议升级到铜镐',
      resource: 'copper_ore',
      baseYield: 1,
      tier: 'mid',
      baseMaxCount: 45,
      baseCooldown: 3000,
      maxUpgrades: { ...POINT_UPGRADE_CAPS },
      upgradeCosts: makePointUpgradeCosts({ resource: 'copper_ore', processed: 'copper_ingot', others: ['coal', 'limestone'], scale: 1.2 }),
      unlockRequires: 'unlock_copper_mine',
    },
    iron_mine: {
      id: 'iron_mine',
      name: '铁矿',
      icon: '🗻',
      description: '开采铁矿石（高级）。建议使用铁镐',
      resource: 'iron_ore',
      baseYield: 1,
      tier: 'high',
      baseMaxCount: 75,
      baseCooldown: 4000,
      maxUpgrades: { ...POINT_UPGRADE_CAPS },
      upgradeCosts: makePointUpgradeCosts({ resource: 'iron_ore', processed: 'iron_ingot', others: ['coke', 'limestone'], scale: 1.4 }),
      unlockRequires: 'unlock_iron_mine',
    },
    coal_mine: {
      id: 'coal_mine',
      name: '煤矿',
      icon: '🕳️',
      description: '开采煤炭（中级）。石镐偏慢，建议升级到铜镐',
      resource: 'coal',
      baseYield: 1,
      tier: 'mid',
      baseMaxCount: 40,
      baseCooldown: 2500,
      maxUpgrades: { ...POINT_UPGRADE_CAPS },
      upgradeCosts: makePointUpgradeCosts({ resource: 'coal', processed: 'coke', others: ['limestone', 'clay'], scale: 1.2 }),
      unlockRequires: 'unlock_coal_mine',
    },
    gravel_bed: {
      id: 'gravel_bed',
      name: '砂砾滩',
      icon: '🏜️',
      description: '采集砂砾（低级）。可烧制成玻璃',
      resource: 'gravel',
      baseYield: 1,
      tier: 'low',
      baseMaxCount: 24,
      baseCooldown: 2000,
      maxUpgrades: { ...POINT_UPGRADE_CAPS },
      upgradeCosts: makePointUpgradeCosts({ resource: 'gravel', processed: 'glass', others: ['clay', 'stone'] }),
      unlockRequires: 'unlock_gravel',
    },
    tin_mine: {
      id: 'tin_mine',
      name: '锡矿',
      icon: '🪙',
      description: '开采锡矿（中级）。可与铜合铸青铜',
      resource: 'tin_ore',
      baseYield: 1,
      tier: 'mid',
      baseMaxCount: 42,
      baseCooldown: 2800,
      maxUpgrades: { ...POINT_UPGRADE_CAPS },
      upgradeCosts: makePointUpgradeCosts({ resource: 'tin_ore', processed: 'bronze', others: ['copper_ore', 'coal'], scale: 1.2 }),
      unlockRequires: 'unlock_tin_mine',
    },
    limestone_quarry: {
      id: 'limestone_quarry',
      name: '石灰岩场',
      icon: '▫️',
      description: '开采石灰石（中级）。可烧制石灰',
      resource: 'limestone',
      baseYield: 1,
      tier: 'mid',
      baseMaxCount: 40,
      baseCooldown: 2600,
      maxUpgrades: { ...POINT_UPGRADE_CAPS },
      upgradeCosts: makePointUpgradeCosts({ resource: 'limestone', processed: 'lime', others: ['gravel', 'clay'], scale: 1.15 }),
      unlockRequires: 'unlock_limestone',
    },
    silver_mine: {
      id: 'silver_mine',
      name: '银矿',
      icon: '🔹',
      description: '开采银矿（高级）。建议使用铁镐',
      resource: 'silver_ore',
      baseYield: 1,
      tier: 'high',
      baseMaxCount: 72,
      baseCooldown: 3500,
      maxUpgrades: { ...POINT_UPGRADE_CAPS },
      upgradeCosts: makePointUpgradeCosts({ resource: 'silver_ore', processed: 'silver_ingot', others: ['coal', 'iron_ore'], scale: 1.4 }),
      unlockRequires: 'unlock_silver_mine',
    },
    sulfur_vent: {
      id: 'sulfur_vent',
      name: '硫气孔',
      icon: '🟡',
      description: '采集硫磺（高级）。可制火药',
      resource: 'sulfur',
      baseYield: 1,
      tier: 'high',
      baseMaxCount: 70,
      baseCooldown: 3200,
      maxUpgrades: { ...POINT_UPGRADE_CAPS },
      upgradeCosts: makePointUpgradeCosts({ resource: 'sulfur', processed: 'gunpowder', others: ['coal', 'limestone'], scale: 1.35 }),
      unlockRequires: 'unlock_sulfur',
    },
    gold_mine: {
      id: 'gold_mine',
      name: '金矿',
      icon: '🟨',
      description: '开采金矿（终极）。低级工具几乎无效',
      resource: 'gold_ore',
      baseYield: 1,
      tier: 'ultimate',
      baseMaxCount: 130,
      baseCooldown: 5000,
      maxUpgrades: { ...POINT_UPGRADE_CAPS },
      upgradeCosts: makePointUpgradeCosts({ resource: 'gold_ore', processed: 'gold_ingot', others: ['glass', 'polished_crystal'], scale: 1.6 }),
      unlockRequires: 'unlock_gold_mine',
    },
    crystal_cave: {
      id: 'crystal_cave',
      name: '水晶洞',
      icon: '💎',
      description: '开采水晶（终极）。可抛光为终局材料',
      resource: 'crystal',
      baseYield: 1,
      tier: 'ultimate',
      baseMaxCount: 130,
      baseCooldown: 5500,
      maxUpgrades: { ...POINT_UPGRADE_CAPS },
      upgradeCosts: makePointUpgradeCosts({ resource: 'crystal', processed: 'polished_crystal', others: ['glass', 'gold_ore'], scale: 1.6 }),
      unlockRequires: 'unlock_crystal',
    },
    resin_grove: {
      id: 'resin_grove',
      name: '松脂林',
      icon: '🍯',
      description: '采集树脂（低级）。可提炼松香，供合成与工具柄粘合',
      resource: 'resin',
      baseYield: 1,
      tier: 'low',
      baseMaxCount: 22,
      baseCooldown: 2200,
      maxUpgrades: { ...POINT_UPGRADE_CAPS },
      upgradeCosts: makePointUpgradeCosts({ resource: 'resin', processed: 'pitch', others: ['wood', 'plank'] }),
      unlockRequires: 'unlock_resin',
    },
    zinc_mine: {
      id: 'zinc_mine',
      name: '锌矿',
      icon: '🔘',
      description: '开采锌矿（中级）。可与铜铸黄铜',
      resource: 'zinc_ore',
      baseYield: 1,
      tier: 'mid',
      baseMaxCount: 42,
      baseCooldown: 2700,
      maxUpgrades: { ...POINT_UPGRADE_CAPS },
      upgradeCosts: makePointUpgradeCosts({ resource: 'zinc_ore', processed: 'brass', others: ['copper_ore', 'coal'], scale: 1.2 }),
      unlockRequires: 'unlock_zinc_mine',
    },
    obsidian_deposit: {
      id: 'obsidian_deposit',
      name: '黑曜岩',
      icon: '⬛',
      description: '开采黑曜石（高级）。无需再加工，可直接用于升级与工具',
      resource: 'obsidian',
      baseYield: 1,
      tier: 'high',
      baseMaxCount: 72,
      baseCooldown: 3600,
      maxUpgrades: { ...POINT_UPGRADE_CAPS },
      upgradeCosts: makePointUpgradeCosts({ resource: 'obsidian', processed: 'obsidian', others: ['iron_ingot', 'gunpowder'], scale: 1.4 }),
      unlockRequires: 'unlock_obsidian',
    },
    meteor_crater: {
      id: 'meteor_crater',
      name: '陨石坑',
      icon: '☄️',
      description: '采集陨石（终极）。可冶炼陨铁',
      resource: 'meteorite',
      baseYield: 1,
      tier: 'ultimate',
      baseMaxCount: 130,
      baseCooldown: 6000,
      maxUpgrades: { ...POINT_UPGRADE_CAPS },
      upgradeCosts: makePointUpgradeCosts({ resource: 'meteorite', processed: 'star_metal', others: ['gold_ingot', 'polished_crystal'], scale: 1.7 }),
      unlockRequires: 'unlock_meteor',
    },
    farm: {
      id: 'farm',
      name: '农场',
      icon: '🌾',
      description: '耕作产出食物（高于浆果）。每座最多 4 人；可建造多座叠加人数上限。单座满员约供 25 人一天口粮',
      resource: 'food',
      baseYield: 1,
      baseMaxCount: 5,
      baseCooldown: 0,
      maxWorkers: 4,
      canBuildMultiple: true,
      extraBuildBaseCost: { wood: 25, clay: 18, food: 12 },
      extraBuildCostBump: { mult: 1.3, add: 8 },
      maxUpgrades: { count: 0, cooldown: 0, double: 0, efficiency: 2 },
      upgradeCosts: { count: [], cooldown: [], double: [] },
      /** 升到对应等级时的单价：约等于按涨价累加「再建 N 座」的总价 */
      efficiencyUpgradeBuilds: [2, 5],
      efficiencySpeedByLevel: { 1: 0.15, 2: 0.3 },
      unlockRequires: 'unlock_farm',
      isFoodPoint: true,
    },
    pasture: {
      id: 'pasture',
      name: '牧场',
      icon: '🐄',
      description: '畜牧产出食物。每座最多 8 人；可建造多座叠加人数上限。单座 4 人约供 40，满员约 80',
      resource: 'food',
      baseYield: 1,
      baseMaxCount: 3,
      baseCooldown: 0,
      maxWorkers: 8,
      canBuildMultiple: true,
      extraBuildBaseCost: { brick: 15, plank: 20, food: 25 },
      extraBuildCostBump: { mult: 1.3, add: 10 },
      maxUpgrades: { count: 0, cooldown: 0, double: 0, efficiency: 2 },
      upgradeCosts: { count: [], cooldown: [], double: [] },
      efficiencyUpgradeBuilds: [2, 5],
      efficiencySpeedByLevel: { 1: 0.15, 2: 0.3 },
      unlockRequires: 'unlock_pasture',
      isFoodPoint: true,
    },
    treasure_chest: {
      id: 'treasure_chest',
      name: '宝箱',
      icon: '📦',
      description: '开启宝箱获得随机资源。宝箱不会自然刷新，需从其他资源点开采掉落',
      isTreasureChest: true,
      baseMaxCount: 4,
      baseCooldown: 500,
      maxUpgrades: { dropRate: 8, rewardTypes: 3, rewardAmount: 3 },
      unlockRequires: 'unlock_treasure_chest',
    },
  },

  recipes: [
    {
      id: 'craft_plank',
      name: '制作木板',
      icon: '🟫',
      description: '5木头合成1木板',
      inputs: { wood: 5 },
      outputs: { plank: 1 },
      requires: 'unlock_plank_craft',
      baseMaxCount: 12,
      baseCooldown: 2000,
    },
    {
      id: 'craft_brick',
      name: '烧制砖块',
      icon: '🧱',
      description: '5黏土烧制1砖',
      inputs: { clay: 5 },
      outputs: { brick: 1 },
      requires: 'unlock_brick_craft',
      baseMaxCount: 10,
      baseCooldown: 2500,
    },
    {
      id: 'smelt_copper',
      name: '冶炼铜锭',
      icon: '🔶',
      description: '2铜矿冶炼1铜锭',
      inputs: { copper_ore: 2 },
      outputs: { copper_ingot: 1 },
      requires: 'unlock_copper_smelt',
      usesFurnace: true,
      baseMaxCount: 8,
      baseCooldown: 3000,
    },
    {
      id: 'craft_gear',
      name: '制造齿轮',
      icon: '⚙️',
      description: '2铜锭+1松香制造1齿轮',
      inputs: { copper_ingot: 2, pitch: 1 },
      outputs: { gear: 1 },
      requires: 'unlock_gear_craft',
      baseMaxCount: 12,
      baseCooldown: 4000,
    },
    {
      id: 'smelt_iron',
      name: '冶炼铁锭',
      icon: '⬜',
      description: '2铁矿+1煤炭冶炼1铁锭',
      inputs: { iron_ore: 2, coal: 1 },
      outputs: { iron_ingot: 1 },
      requires: 'unlock_iron_smelt',
      usesFurnace: true,
      baseMaxCount: 12,
      baseCooldown: 4000,
    },
    {
      id: 'smelt_steel',
      name: '锻造钢材',
      icon: '🔩',
      description: '2铁锭+1焦炭锻造1钢（需升级熔炉）',
      inputs: { iron_ingot: 2, coke: 1 },
      outputs: { steel: 1 },
      requires: 'unlock_steel_smelt',
      usesFurnace: true,
      baseMaxCount: 14,
      baseCooldown: 5000,
    },
    {
      id: 'craft_lime',
      name: '烧制石灰',
      icon: '⬜',
      description: '4石灰石烧制1石灰',
      inputs: { limestone: 4 },
      outputs: { lime: 1 },
      requires: 'unlock_lime_craft',
      usesFurnace: true,
      baseMaxCount: 10,
      baseCooldown: 3000,
    },
    {
      id: 'craft_bronze',
      name: '铸造青铜',
      icon: '🥉',
      description: '2铜锭+1锡矿铸成1青铜',
      inputs: { copper_ingot: 2, tin_ore: 1 },
      outputs: { bronze: 1 },
      requires: 'unlock_bronze_craft',
      usesFurnace: true,
      baseMaxCount: 10,
      baseCooldown: 3500,
    },
    {
      id: 'smelt_silver',
      name: '冶炼银锭',
      icon: '🪞',
      description: '2银矿+1煤炭冶炼1银锭',
      inputs: { silver_ore: 2, coal: 1 },
      outputs: { silver_ingot: 1 },
      requires: 'unlock_silver_smelt',
      usesFurnace: true,
      baseMaxCount: 12,
      baseCooldown: 4000,
    },
    {
      id: 'craft_gunpowder',
      name: '配制火药',
      icon: '💥',
      description: '2硫磺+1煤炭配制1火药',
      inputs: { sulfur: 2, coal: 1 },
      outputs: { gunpowder: 1 },
      requires: 'unlock_gunpowder',
      baseMaxCount: 10,
      baseCooldown: 3500,
    },
    {
      id: 'smelt_gold',
      name: '冶炼金锭',
      icon: '🥇',
      description: '2金矿+1煤炭冶炼1金锭',
      inputs: { gold_ore: 2, coal: 1 },
      outputs: { gold_ingot: 1 },
      requires: 'unlock_gold_smelt',
      usesFurnace: true,
      baseMaxCount: 14,
      baseCooldown: 5000,
    },
    {
      id: 'craft_polished_crystal',
      name: '抛光水晶',
      icon: '💠',
      description: '1水晶+1玻璃抛光为1抛光水晶',
      inputs: { crystal: 1, glass: 1 },
      outputs: { polished_crystal: 1 },
      requires: 'unlock_crystal_polish',
      baseMaxCount: 12,
      baseCooldown: 4500,
    },
    {
      id: 'craft_pitch',
      name: '提炼松香',
      icon: '🟤',
      description: '3树脂提炼1松香',
      inputs: { resin: 3 },
      outputs: { pitch: 1 },
      requires: 'unlock_pitch',
      baseMaxCount: 8,
      baseCooldown: 2500,
    },
    {
      id: 'craft_stone_slab',
      name: '切割石板',
      icon: '▦',
      description: '4石头加工为1石板',
      inputs: { stone: 4 },
      outputs: { stone_slab: 1 },
      requires: 'unlock_quarry',
      baseMaxCount: 8,
      baseCooldown: 2200,
    },
    {
      id: 'craft_glass',
      name: '烧制玻璃',
      icon: '🪟',
      description: '3砂砾+1石灰烧制1玻璃',
      inputs: { gravel: 3, lime: 1 },
      outputs: { glass: 1 },
      requires: 'unlock_lime_craft',
      usesFurnace: true,
      baseMaxCount: 9,
      baseCooldown: 2800,
    },
    {
      id: 'craft_coke',
      name: '煅烧焦炭',
      icon: '⬛',
      description: '3煤炭煅烧1焦炭（资源点升级材料）',
      inputs: { coal: 3 },
      outputs: { coke: 1 },
      requires: 'unlock_coal_mine',
      usesFurnace: true,
      baseMaxCount: 9,
      baseCooldown: 2800,
    },
    {
      id: 'craft_brass',
      name: '铸造黄铜',
      icon: '🟡',
      description: '1铜锭+1锌矿铸成1黄铜',
      inputs: { copper_ingot: 1, zinc_ore: 1 },
      outputs: { brass: 1 },
      requires: 'unlock_brass_craft',
      usesFurnace: true,
      baseMaxCount: 10,
      baseCooldown: 3200,
    },
    {
      id: 'smelt_star_metal',
      name: '冶炼陨铁',
      icon: '🌟',
      description: '2陨石+1煤炭冶炼1陨铁',
      inputs: { meteorite: 2, coal: 1 },
      outputs: { star_metal: 1 },
      requires: 'unlock_star_metal',
      usesFurnace: true,
      baseMaxCount: 14,
      baseCooldown: 5500,
    },
    // —— 工具：Lv1 仅初级原料；Lv2+ 对应档「加工+原料」，各配方尽量不重复 ——
    {
      id: 'craft_axe_1',
      name: '木斧',
      icon: '🪓',
      description: '1级斧（初级原料）：木头+树脂，砍伐树木与松脂林',
      inputs: { wood: 10, resin: 6 },
      outputs: {},
      outputTools: { axe: { level: 1, amount: 1 } },
      requires: 'unlock_tool_crafting',
      baseMaxCount: 8,
      baseCooldown: 2000,
      isToolRecipe: true,
    },
    {
      id: 'craft_axe_2',
      name: '青铜斧',
      icon: '🪓',
      description: '2级斧（中级）：青铜+锡矿，消耗1把木斧',
      inputs: { bronze: 3, tin_ore: 4 },
      inputTools: { axe: { level: 1, amount: 1 } },
      outputs: {},
      outputTools: { axe: { level: 2, amount: 1 } },
      requires: 'unlock_bronze_craft',
      baseMaxCount: 9,
      baseCooldown: 2500,
      isToolRecipe: true,
    },
    {
      id: 'craft_axe_3',
      name: '钢斧',
      icon: '🪓',
      description: '3级斧（高级）：钢+铁矿，消耗1把青铜斧',
      inputs: { steel: 2, iron_ore: 6 },
      inputTools: { axe: { level: 2, amount: 1 } },
      outputs: {},
      outputTools: { axe: { level: 3, amount: 1 } },
      requires: 'unlock_steel_smelt',
      baseMaxCount: 10,
      baseCooldown: 3000,
      isToolRecipe: true,
    },
    {
      id: 'craft_axe_4',
      name: '金斧',
      icon: '🪓',
      description: '4级斧（终极）：金锭+金矿，消耗1把钢斧',
      inputs: { gold_ingot: 2, gold_ore: 5 },
      inputTools: { axe: { level: 3, amount: 1 } },
      outputs: {},
      outputTools: { axe: { level: 4, amount: 1 } },
      requires: 'unlock_gold_smelt',
      baseMaxCount: 12,
      baseCooldown: 3500,
      isToolRecipe: true,
    },
    {
      id: 'craft_pickaxe_1',
      name: '石镐',
      icon: '⛏️',
      description: '1级镐（初级原料）：木头+石头，采矿与采石',
      inputs: { wood: 6, stone: 10 },
      outputs: {},
      outputTools: { pickaxe: { level: 1, amount: 1 } },
      requires: 'unlock_tool_crafting',
      baseMaxCount: 8,
      baseCooldown: 2000,
      isToolRecipe: true,
    },
    {
      id: 'craft_pickaxe_2',
      name: '黄铜镐',
      icon: '⛏️',
      description: '2级镐（中级）：黄铜+锌矿，消耗1把石镐',
      inputs: { brass: 3, zinc_ore: 5 },
      inputTools: { pickaxe: { level: 1, amount: 1 } },
      outputs: {},
      outputTools: { pickaxe: { level: 2, amount: 1 } },
      requires: 'unlock_brass_craft',
      baseMaxCount: 9,
      baseCooldown: 2500,
      isToolRecipe: true,
    },
    {
      id: 'craft_pickaxe_3',
      name: '银镐',
      icon: '⛏️',
      description: '3级镐（高级）：银锭+银矿，消耗1把黄铜镐',
      inputs: { silver_ingot: 3, silver_ore: 6 },
      inputTools: { pickaxe: { level: 2, amount: 1 } },
      outputs: {},
      outputTools: { pickaxe: { level: 3, amount: 1 } },
      requires: 'unlock_silver_smelt',
      baseMaxCount: 10,
      baseCooldown: 3000,
      isToolRecipe: true,
    },
    {
      id: 'craft_pickaxe_4',
      name: '晶镐',
      icon: '⛏️',
      description: '4级镐（终极）：抛光水晶+水晶，消耗1把银镐',
      inputs: { polished_crystal: 2, crystal: 4 },
      inputTools: { pickaxe: { level: 3, amount: 1 } },
      outputs: {},
      outputTools: { pickaxe: { level: 4, amount: 1 } },
      requires: 'unlock_crystal_polish',
      baseMaxCount: 12,
      baseCooldown: 3500,
      isToolRecipe: true,
    },
    {
      id: 'craft_shovel_1',
      name: '木铲',
      icon: '🥄',
      description: '1级铲（初级原料）：挖黏土与砂砾',
      inputs: { wood: 6, clay: 8 },
      outputs: {},
      outputTools: { shovel: { level: 1, amount: 1 } },
      requires: 'unlock_tool_crafting',
      baseMaxCount: 8,
      baseCooldown: 2000,
      isToolRecipe: true,
    },
    {
      id: 'craft_shovel_2',
      name: '灰浆铲',
      icon: '🥄',
      description: '2级铲（中级）：石灰+煤炭，消耗1把木铲',
      inputs: { lime: 4, coal: 6 },
      inputTools: { shovel: { level: 1, amount: 1 } },
      outputs: {},
      outputTools: { shovel: { level: 2, amount: 1 } },
      requires: 'unlock_lime_craft',
      baseMaxCount: 9,
      baseCooldown: 2500,
      isToolRecipe: true,
    },
    {
      id: 'craft_shovel_3',
      name: '曜石铲',
      icon: '🥄',
      description: '3级铲（高级）：火药+黑曜石，消耗1把灰浆铲',
      inputs: { gunpowder: 3, obsidian: 5 },
      inputTools: { shovel: { level: 2, amount: 1 } },
      outputs: {},
      outputTools: { shovel: { level: 3, amount: 1 } },
      requires: 'unlock_gunpowder',
      baseMaxCount: 10,
      baseCooldown: 3000,
      isToolRecipe: true,
    },
    {
      id: 'craft_shovel_4',
      name: '陨铲',
      icon: '🥄',
      description: '4级铲（终极）：陨铁+陨石，消耗1把曜石铲',
      inputs: { star_metal: 2, meteorite: 4 },
      inputTools: { shovel: { level: 3, amount: 1 } },
      outputs: {},
      outputTools: { shovel: { level: 4, amount: 1 } },
      requires: 'unlock_star_metal',
      baseMaxCount: 12,
      baseCooldown: 3500,
      isToolRecipe: true,
    },
    // —— 战争武器：木→青铜→铁→钢 ——
    {
      id: 'craft_bow_1',
      name: '木弓',
      icon: '🏹',
      description: '1级弓：木+树脂。远程岗需弓/弩才可上岗',
      inputs: { wood: 8, resin: 5 },
      outputs: {},
      outputTools: { bow: { level: 1, amount: 1 } },
      requires: 'unlock_tool_crafting',
      baseMaxCount: 8,
      baseCooldown: 2000,
      isToolRecipe: true,
    },
    {
      id: 'craft_bow_2',
      name: '青铜弓',
      icon: '🏹',
      description: '2级弓：青铜+木板，消耗1张木弓',
      inputs: { bronze: 2, plank: 4 },
      inputTools: { bow: { level: 1, amount: 1 } },
      outputs: {},
      outputTools: { bow: { level: 2, amount: 1 } },
      requires: 'unlock_bronze_craft',
      baseMaxCount: 9,
      baseCooldown: 2500,
      isToolRecipe: true,
    },
    {
      id: 'craft_bow_3',
      name: '铁弓',
      icon: '🏹',
      description: '3级弓：铁锭+木板，消耗1张青铜弓',
      inputs: { iron_ingot: 2, plank: 5 },
      inputTools: { bow: { level: 2, amount: 1 } },
      outputs: {},
      outputTools: { bow: { level: 3, amount: 1 } },
      requires: 'unlock_iron_smelt',
      baseMaxCount: 10,
      baseCooldown: 3000,
      isToolRecipe: true,
    },
    {
      id: 'craft_bow_4',
      name: '钢弓',
      icon: '🏹',
      description: '4级弓：钢+焦炭，消耗1张铁弓',
      inputs: { steel: 2, coke: 3 },
      inputTools: { bow: { level: 3, amount: 1 } },
      outputs: {},
      outputTools: { bow: { level: 4, amount: 1 } },
      requires: 'unlock_steel_smelt',
      baseMaxCount: 12,
      baseCooldown: 3500,
      isToolRecipe: true,
    },
    {
      id: 'craft_crossbow_1',
      name: '木弩',
      icon: '🎯',
      description: '1级弩：木+石头。伤害高于弓、射速较慢',
      inputs: { wood: 10, stone: 6 },
      outputs: {},
      outputTools: { crossbow: { level: 1, amount: 1 } },
      requires: 'unlock_tool_crafting',
      baseMaxCount: 8,
      baseCooldown: 2200,
      isToolRecipe: true,
    },
    {
      id: 'craft_crossbow_2',
      name: '青铜弩',
      icon: '🎯',
      description: '2级弩：青铜+齿轮，消耗1张木弩',
      inputs: { bronze: 3, gear: 2 },
      inputTools: { crossbow: { level: 1, amount: 1 } },
      outputs: {},
      outputTools: { crossbow: { level: 2, amount: 1 } },
      requires: 'unlock_bronze_craft',
      baseMaxCount: 9,
      baseCooldown: 2700,
      isToolRecipe: true,
    },
    {
      id: 'craft_crossbow_3',
      name: '铁弩',
      icon: '🎯',
      description: '3级弩：铁锭+齿轮，消耗1张青铜弩',
      inputs: { iron_ingot: 3, gear: 3 },
      inputTools: { crossbow: { level: 2, amount: 1 } },
      outputs: {},
      outputTools: { crossbow: { level: 3, amount: 1 } },
      requires: 'unlock_iron_smelt',
      baseMaxCount: 10,
      baseCooldown: 3200,
      isToolRecipe: true,
    },
    {
      id: 'craft_crossbow_4',
      name: '钢弩',
      icon: '🎯',
      description: '4级弩：钢+焦炭，消耗1张铁弩',
      inputs: { steel: 2, coke: 4 },
      inputTools: { crossbow: { level: 3, amount: 1 } },
      outputs: {},
      outputTools: { crossbow: { level: 4, amount: 1 } },
      requires: 'unlock_steel_smelt',
      baseMaxCount: 12,
      baseCooldown: 3600,
      isToolRecipe: true,
    },
    {
      id: 'craft_sword_1',
      name: '木剑',
      icon: '🗡️',
      description: '1级剑：木+树脂。近战岗需剑或斧',
      inputs: { wood: 8, resin: 4 },
      outputs: {},
      outputTools: { sword: { level: 1, amount: 1 } },
      requires: 'unlock_tool_crafting',
      baseMaxCount: 8,
      baseCooldown: 2000,
      isToolRecipe: true,
    },
    {
      id: 'craft_sword_2',
      name: '青铜剑',
      icon: '🗡️',
      description: '2级剑：青铜+锡矿，消耗1把木剑',
      inputs: { bronze: 3, tin_ore: 3 },
      inputTools: { sword: { level: 1, amount: 1 } },
      outputs: {},
      outputTools: { sword: { level: 2, amount: 1 } },
      requires: 'unlock_bronze_craft',
      baseMaxCount: 9,
      baseCooldown: 2500,
      isToolRecipe: true,
    },
    {
      id: 'craft_sword_3',
      name: '铁剑',
      icon: '🗡️',
      description: '3级剑：铁锭+铁矿，消耗1把青铜剑',
      inputs: { iron_ingot: 3, iron_ore: 4 },
      inputTools: { sword: { level: 2, amount: 1 } },
      outputs: {},
      outputTools: { sword: { level: 3, amount: 1 } },
      requires: 'unlock_iron_smelt',
      baseMaxCount: 10,
      baseCooldown: 3000,
      isToolRecipe: true,
    },
    {
      id: 'craft_sword_4',
      name: '钢剑',
      icon: '🗡️',
      description: '4级剑：钢+铁矿，消耗1把铁剑',
      inputs: { steel: 2, iron_ore: 5 },
      inputTools: { sword: { level: 3, amount: 1 } },
      outputs: {},
      outputTools: { sword: { level: 4, amount: 1 } },
      requires: 'unlock_steel_smelt',
      baseMaxCount: 12,
      baseCooldown: 3500,
      isToolRecipe: true,
    },
    {
      id: 'craft_shield_1',
      name: '木盾',
      icon: '🛡️',
      description: '1级盾：木+树脂。给近战附加，不占编制',
      inputs: { wood: 10, resin: 4 },
      outputs: {},
      outputTools: { shield: { level: 1, amount: 1 } },
      requires: 'unlock_tool_crafting',
      baseMaxCount: 8,
      baseCooldown: 2000,
      isToolRecipe: true,
    },
    {
      id: 'craft_shield_2',
      name: '青铜盾',
      icon: '🛡️',
      description: '2级盾：青铜+木板，消耗1面木盾',
      inputs: { bronze: 2, plank: 5 },
      inputTools: { shield: { level: 1, amount: 1 } },
      outputs: {},
      outputTools: { shield: { level: 2, amount: 1 } },
      requires: 'unlock_bronze_craft',
      baseMaxCount: 9,
      baseCooldown: 2500,
      isToolRecipe: true,
    },
    {
      id: 'craft_shield_3',
      name: '铁盾',
      icon: '🛡️',
      description: '3级盾：铁锭+石板，消耗1面青铜盾',
      inputs: { iron_ingot: 3, stone_slab: 4 },
      inputTools: { shield: { level: 2, amount: 1 } },
      outputs: {},
      outputTools: { shield: { level: 3, amount: 1 } },
      requires: 'unlock_iron_smelt',
      baseMaxCount: 10,
      baseCooldown: 3000,
      isToolRecipe: true,
    },
    {
      id: 'craft_shield_4',
      name: '钢盾',
      icon: '🛡️',
      description: '4级盾：钢+砖，消耗1面铁盾',
      inputs: { steel: 2, brick: 5 },
      inputTools: { shield: { level: 3, amount: 1 } },
      outputs: {},
      outputTools: { shield: { level: 4, amount: 1 } },
      requires: 'unlock_steel_smelt',
      baseMaxCount: 12,
      baseCooldown: 3500,
      isToolRecipe: true,
    },
    {
      id: 'craft_armor_1',
      name: '木甲',
      icon: '🥋',
      description: '1级铠甲：提高减伤与生命；自动穿给编制（优先近战）',
      inputs: { wood: 12, resin: 6, plank: 4 },
      outputs: {},
      outputTools: { armor: { level: 1, amount: 1 } },
      requires: 'unlock_tool_crafting',
      baseMaxCount: 8,
      baseCooldown: 2400,
      isToolRecipe: true,
    },
    {
      id: 'craft_armor_2',
      name: '青铜甲',
      icon: '🥋',
      description: '2级铠甲：青铜+木板，消耗1件木甲',
      inputs: { bronze: 4, plank: 6 },
      inputTools: { armor: { level: 1, amount: 1 } },
      outputs: {},
      outputTools: { armor: { level: 2, amount: 1 } },
      requires: 'unlock_bronze_craft',
      baseMaxCount: 9,
      baseCooldown: 2800,
      isToolRecipe: true,
    },
    {
      id: 'craft_armor_3',
      name: '铁甲',
      icon: '🥋',
      description: '3级铠甲：铁锭+皮革替代（木板），消耗1件青铜甲',
      inputs: { iron_ingot: 4, brick: 4 },
      inputTools: { armor: { level: 2, amount: 1 } },
      outputs: {},
      outputTools: { armor: { level: 3, amount: 1 } },
      requires: 'unlock_iron_smelt',
      baseMaxCount: 10,
      baseCooldown: 3200,
      isToolRecipe: true,
    },
    {
      id: 'craft_armor_4',
      name: '钢甲',
      icon: '🥋',
      description: '4级铠甲：钢+焦炭，消耗1件铁甲',
      inputs: { steel: 3, coke: 4 },
      inputTools: { armor: { level: 3, amount: 1 } },
      outputs: {},
      outputTools: { armor: { level: 4, amount: 1 } },
      requires: 'unlock_steel_smelt',
      baseMaxCount: 12,
      baseCooldown: 3600,
      isToolRecipe: true,
    },
  ],

  // 村民工具类型（库存按等级：toolInventory[id][level]）
  villagerTools: {
    axe: {
      id: 'axe',
      name: '斧头',
      icon: '🪓',
      targets: ['forest', 'resin_grove'],
      maxLevel: 4,
      levelNames: { 1: '木斧', 2: '青铜斧', 3: '钢斧', 4: '金斧' },
    },
    pickaxe: {
      id: 'pickaxe',
      name: '镐子',
      icon: '⛏️',
      targets: [
        'quarry', 'copper_mine', 'iron_mine', 'coal_mine',
        'tin_mine', 'limestone_quarry', 'zinc_mine',
        'silver_mine', 'sulfur_vent', 'obsidian_deposit',
        'gold_mine', 'crystal_cave', 'meteor_crater',
      ],
      maxLevel: 4,
      levelNames: { 1: '石镐', 2: '黄铜镐', 3: '银镐', 4: '晶镐' },
    },
    shovel: {
      id: 'shovel',
      name: '铲子',
      icon: '🥄',
      targets: ['clay_pit', 'gravel_bed'],
      maxLevel: 4,
      levelNames: { 1: '木铲', 2: '灰浆铲', 3: '曜石铲', 4: '陨铲' },
    },
    bow: {
      id: 'bow',
      name: '弓',
      icon: '🏹',
      targets: [],
      combat: true,
      maxLevel: 4,
      levelNames: { 1: '木弓', 2: '青铜弓', 3: '铁弓', 4: '钢弓' },
    },
    crossbow: {
      id: 'crossbow',
      name: '弩',
      icon: '🎯',
      targets: [],
      combat: true,
      maxLevel: 4,
      levelNames: { 1: '木弩', 2: '青铜弩', 3: '铁弩', 4: '钢弩' },
    },
    sword: {
      id: 'sword',
      name: '剑',
      icon: '🗡️',
      targets: [],
      combat: true,
      maxLevel: 4,
      levelNames: { 1: '木剑', 2: '青铜剑', 3: '铁剑', 4: '钢剑' },
    },
    shield: {
      id: 'shield',
      name: '盾',
      icon: '🛡️',
      targets: [],
      combat: true,
      maxLevel: 4,
      levelNames: { 1: '木盾', 2: '青铜盾', 3: '铁盾', 4: '钢盾' },
    },
    armor: {
      id: 'armor',
      name: '铠甲',
      icon: '🥋',
      targets: [],
      combat: true,
      maxLevel: 4,
      levelNames: { 1: '木甲', 2: '青铜甲', 3: '铁甲', 4: '钢甲' },
    },
  },

  housing: {
    startingVillagers: 10,
    /** 初始 5 间 × 容量 2 = 人口上限 10 */
    startingHouses: 5,
    /** 基础房屋人口上限；每升 1 级翻倍 */
    baseCapacity: 2,
    maxHouseLevel: 4,
    breedFoodCost: 10,
    /** 建造：两种初级原料；升级：对应档加工品 + 同主题建材 */
    buildBaseCost: { wood: 20, stone: 15 },
    buildCostBump: { mult: 1.25, add: 5 },
    upgrades: {
      1: {
        name: '木石基座',
        desc: '人口上限翻倍（2→4）：木板铺装 + 石板打底',
        baseCost: { plank: 16, stone_slab: 12 },
        costBump: { mult: 1.2, add: 5 },
      },
      2: {
        name: '砖瓦开窗',
        desc: '人口上限翻倍（4→8）：砖墙 + 玻璃窗 + 中级矿料',
        baseCost: { brick: 14, glass: 10, copper_ore: 12, coal: 10 },
        costBump: { mult: 1.2, add: 5 },
      },
      3: {
        name: '灰浆厅堂',
        desc: '人口上限翻倍（8→16）：石灰砂浆 + 青铜构件 + 铁矿骨架',
        baseCost: { lime: 14, bronze: 10, glass: 8, iron_ore: 16 },
        costBump: { mult: 1.2, add: 6 },
      },
      4: {
        name: '精钢堡垒',
        desc: '人口上限翻倍（16→32）：钢梁 + 银饰 + 黑曜加固',
        baseCost: { steel: 10, iron_ingot: 14, silver_ingot: 8, obsidian: 10 },
        costBump: { mult: 1.2, add: 8 },
      },
    },
  },

  villagerWork: {
    baseSpeed: 0.05,
    // 持工具效率：仅影响村民自动工作，不影响手动点击
    toolSpeedByLevel: { 1: 0.25, 2: 0.5, 3: 1.0, 4: 1.75 },
    baseClickPower: 1,
    // 手动点击由科技「点击强化」升级，不再由工具提供
    tooledSpeed: 0.25,
  },

  /**
   * 日期与食物平衡（徒手采集速度 0.05/秒）：
   * 浆果丛 maxCount=12 → 单人约 0.05/12 食物/秒
   * 4 人采集 → 1/60 食物/秒
   * 一天现实时长 900 秒；夜间 22:00–06:00（占 1/3）村民休息不自动工作
   * → 日间自动工作约 600 秒 → 10 食物，刚好够 10 人口（每人 1 份/天）
   * 农场每座 4 人 maxCount=5 → 约 24 食物/天；可多座，人数上限叠加
   * 牧场每座 maxCount=3：4 人 → 40；满 8 人 → 80；可多座叠加上限
   */
  calendar: {
    dayDurationMs: 900000,
    foodPerVillager: 1,
    startingFood: 7,
    /** 休息时段 [restStartHour, 24) ∪ [0, restEndHour) */
    restStartHour: 22,
    restEndHour: 6,
  },

  /** 新开档初始库存（与 calendar.startingFood 对齐） */
  startingResources: {
    food: 7,
    wood: 3,
  },

  /** 新开档已解锁科技 */
  startingTechs: ['unlock_tool_crafting', 'unlock_treasure_chest'],

  /**
   * 首次攒够第 N 次森林砍伐时，固定掉落引导宝箱（含一把木斧的材料）
   */
  starterChest: {
    afterForestHarvests: 2,
    tip: '🎁 采集资源点时有概率掉落宝箱！这次固定掉了一个——打开后可获得制作木斧的材料。',
    rewards: [
      { res: 'wood', amt: 10 },
      { res: 'resin', amt: 6 },
    ],
  },

  /** 生产订单完成后固定冷却（毫秒） */
  craftOrderCooldownMs: 250,

  toolUnlockMap: {},

  techTree: [
    {
      id: 'unlock_workbench',
      name: '工作台',
      icon: '🔨',
      description: '解锁工作台，开启科技研发',
      cost: { wood: 5 },
      requires: null,
      branch: 'root',
    },
    {
      id: 'unlock_tool_crafting',
      name: '工具制作',
      icon: '🪓',
      description: '在工具页制作斧/镐/铲，以及弓/弩/剑/盾/铠甲（战争用）；高等级消耗低级工具升级',
      cost: { wood: 12, resin: 8, clay: 6 },
      requires: 'unlock_resin',
      branch: 'tools',
    },
    {
      id: 'unlock_farm',
      name: '开设农场',
      icon: '🌾',
      description: '解锁农场（每座最多 4 人，可再建多座叠加上限）。单座满员约供 25 人一天口粮',
      cost: { wood: 20, clay: 15, food: 10 },
      requires: 'unlock_clay_pit',
      branch: 'workers',
    },
    {
      id: 'unlock_pasture',
      name: '开设牧场',
      icon: '🐄',
      description: '解锁牧场（每座最多 8 人，可再建多座叠加上限）。单座 4 人约供 40，满员约 80',
      cost: { brick: 18, plank: 20, glass: 8, food: 30 },
      requires: 'unlock_farm',
      branch: 'workers',
    },
    {
      id: 'unlock_offline_cap',
      name: '离线延时',
      icon: '🌙',
      description: '村民离线继续生产，上限+30分钟（默认30分钟，满级8小时）',
      cost: { wood: 25, plank: 5 },
      requires: 'unlock_workbench',
      branch: 'workers',
      repeatable: true,
      repeatCost: { wood: 40, plank: 15, stone: 10 },
      maxRepeat: 15,
    },
    {
      id: 'unlock_auto_click',
      name: '连点加速',
      icon: '👆',
      description: '按住鼠标自动点击，每次升级减少按住冷却（默认1秒/次，满级0.2秒/次）',
      cost: { wood: 15 },
      requires: 'unlock_workbench',
      branch: 'root',
      repeatable: true,
      repeatCost: { wood: 25, plank: 10, stone: 5 },
      maxRepeat: 10,
    },
    {
      id: 'unlock_click_power',
      name: '点击强化',
      icon: '🖱️',
      description: '提升手动点击效率：每级 +1 进度/次（共 4 级）。工具不再影响点击',
      requires: 'unlock_workbench',
      branch: 'root',
      repeatable: true,
      maxRepeat: 4,
      cost: { wood: 20, stone: 15, clay: 15 },
      repeatCosts: [
        { wood: 20, stone: 15, clay: 15 },
        { plank: 12, stone_slab: 10, brick: 10 },
        { glass: 8, copper_ingot: 10, bronze: 6 },
        { iron_ingot: 10, glass: 12, gear: 6 },
      ],
    },
    {
      id: 'unlock_plank_craft',
      name: '木板加工',
      icon: '🟫',
      description: '解锁木板配方，在合成页安排生产（5木头→1木板）',
      cost: { wood: 10 },
      requires: 'unlock_workbench',
      branch: 'craft',
    },
    {
      id: 'unlock_quarry',
      name: '采石场',
      icon: '⛏️',
      description: '解锁采石场资源点',
      cost: { wood: 12, plank: 5 },
      requires: 'unlock_workbench',
      branch: 'mining',
    },
    {
      id: 'unlock_clay_pit',
      name: '黏土坑',
      icon: '🟠',
      description: '解锁黏土坑资源点（前期资源，与石头同级）',
      cost: { wood: 10, plank: 3 },
      requires: 'unlock_workbench',
      branch: 'mining',
    },
    {
      id: 'unlock_gravel',
      name: '砂砾滩',
      icon: '🏜️',
      description: '解锁砂砾滩（低级资源点，铲子采集）',
      cost: { wood: 12, plank: 4, stone: 6 },
      requires: 'unlock_quarry',
      branch: 'mining',
    },
    {
      id: 'unlock_resin',
      name: '松脂林',
      icon: '🍯',
      description: '解锁松脂林（低级），斧头采集树脂',
      cost: { wood: 14, stone: 6 },
      requires: 'unlock_workbench',
      branch: 'mining',
    },
    {
      id: 'unlock_pitch',
      name: '松香提炼',
      icon: '🟤',
      description: '解锁松香配方（3树脂→1松香），用于齿轮等合成',
      cost: { resin: 12, wood: 8 },
      requires: 'unlock_resin',
      branch: 'craft',
    },
    {
      id: 'unlock_brick_craft',
      name: '砖块烧制',
      icon: '🧱',
      description: '解锁砖配方，在合成页安排生产（5黏土→1砖）',
      cost: { clay: 8, wood: 5 },
      requires: 'unlock_clay_pit',
      branch: 'craft',
    },
    {
      id: 'unlock_treasure_chest',
      name: '宝箱',
      icon: '📦',
      description: '解锁宝箱资源点，开采其他资源点有1%概率掉落宝箱',
      cost: { wood: 18, stone: 8, plank: 3, stone_slab: 4 },
      requires: 'unlock_quarry',
      branch: 'mining',
    },
    {
      id: 'unlock_advanced_workbench',
      name: '高级工作台',
      icon: '🏗️',
      description: '解锁更高级的合成配方',
      cost: { plank: 12, stone_slab: 10 },
      requires: 'unlock_plank_craft',
      branch: 'craft',
    },
    {
      id: 'unlock_furnace',
      name: '熔炉',
      icon: '🔥',
      description: '解锁熔炉，可冶炼金属',
      cost: { stone_slab: 16, plank: 10, pitch: 4 },
      requires: 'unlock_advanced_workbench',
      branch: 'smelting',
    },
    {
      id: 'unlock_copper_mine',
      name: '铜矿',
      icon: '🏔️',
      description: '解锁铜矿资源点',
      cost: { plank: 12, stone_slab: 12 },
      requires: 'unlock_furnace',
      branch: 'mining',
    },
    {
      id: 'unlock_copper_smelt',
      name: '铜锭冶炼',
      icon: '🔶',
      description: '解锁铜锭配方，在合成页安排生产',
      cost: { copper_ore: 5 },
      requires: 'unlock_furnace',
      branch: 'smelting',
    },
    {
      id: 'unlock_coal_mine',
      name: '煤矿',
      icon: '🕳️',
      description: '解锁煤矿资源点',
      cost: { stone_slab: 14, plank: 10, coal: 5 },
      requires: 'unlock_furnace',
      branch: 'mining',
    },
    {
      id: 'unlock_tin_mine',
      name: '锡矿',
      icon: '🪙',
      description: '解锁锡矿（中级），可铸造青铜',
      cost: { plank: 18, stone: 14, copper_ore: 8 },
      requires: 'unlock_copper_mine',
      branch: 'mining',
    },
    {
      id: 'unlock_zinc_mine',
      name: '锌矿',
      icon: '🔘',
      description: '解锁锌矿（中级），可铸造黄铜',
      cost: { plank: 16, stone: 12, copper_ore: 10 },
      requires: 'unlock_copper_mine',
      branch: 'mining',
    },
    {
      id: 'unlock_brass_craft',
      name: '黄铜铸造',
      icon: '🟡',
      description: '解锁黄铜：1铜锭+1锌矿→1黄铜',
      cost: { copper_ingot: 5, zinc_ore: 8 },
      requires: 'unlock_zinc_mine',
      branch: 'smelting',
    },
    {
      id: 'unlock_limestone',
      name: '石灰岩场',
      icon: '▫️',
      description: '解锁石灰石采集（中级）',
      cost: { stone: 16, plank: 10, gravel: 12 },
      requires: 'unlock_gravel',
      branch: 'mining',
    },
    {
      id: 'unlock_lime_craft',
      name: '石灰烧制',
      icon: '⬜',
      description: '解锁石灰配方（4石灰石→1石灰，建议已有熔炉）',
      cost: { limestone: 12, coal: 5, brick: 6 },
      requires: 'unlock_limestone',
      branch: 'smelting',
    },
    {
      id: 'unlock_bronze_craft',
      name: '青铜铸造',
      icon: '🥉',
      description: '解锁青铜：2铜锭+1锡矿→1青铜',
      cost: { copper_ingot: 6, tin_ore: 5 },
      requires: 'unlock_tin_mine',
      branch: 'smelting',
    },
    {
      id: 'unlock_gear_craft',
      name: '齿轮制造',
      icon: '⚙️',
      description: '解锁齿轮配方，在合成页安排生产',
      cost: { copper_ingot: 8, pitch: 6 },
      requires: 'unlock_copper_smelt',
      branch: 'craft',
    },
    {
      id: 'unlock_iron_mine',
      name: '铁矿',
      icon: '🗻',
      description: '解锁铁矿资源点',
      cost: { copper_ingot: 10, gear: 3, plank: 20 },
      requires: 'unlock_gear_craft',
      branch: 'mining',
    },
    {
      id: 'unlock_iron_smelt',
      name: '铁锭冶炼',
      icon: '⬜',
      description: '解锁铁锭配方，在合成页安排生产',
      cost: { iron_ore: 5, coal: 3 },
      requires: 'unlock_iron_mine',
      branch: 'smelting',
    },
    {
      id: 'unlock_silver_mine',
      name: '银矿',
      icon: '🔹',
      description: '解锁银矿（高级）',
      cost: { iron_ingot: 8, bronze: 6, gear: 4 },
      requires: 'unlock_iron_smelt',
      branch: 'mining',
    },
    {
      id: 'unlock_sulfur',
      name: '硫气孔',
      icon: '🟡',
      description: '解锁硫磺采集（高级）',
      cost: { iron_ore: 12, coal: 10, brick: 15 },
      requires: 'unlock_iron_mine',
      branch: 'mining',
    },
    {
      id: 'unlock_obsidian',
      name: '黑曜岩',
      icon: '🖤',
      description: '解锁黑曜石采集（高级）',
      cost: { iron_ingot: 6, sulfur: 8, lime: 8 },
      requires: 'unlock_sulfur',
      branch: 'mining',
    },
    {
      id: 'unlock_silver_smelt',
      name: '银锭冶炼',
      icon: '🪞',
      description: '解锁银锭：2银矿+1煤炭→1银锭',
      cost: { silver_ore: 8, coal: 5 },
      requires: 'unlock_silver_mine',
      branch: 'smelting',
    },
    {
      id: 'unlock_gunpowder',
      name: '火药配制',
      icon: '💥',
      description: '解锁火药：2硫磺+1煤炭→1火药',
      cost: { sulfur: 10, coal: 8 },
      requires: 'unlock_sulfur',
      branch: 'craft',
    },
    {
      id: 'unlock_furnace_upgrade',
      name: '熔炉升级',
      icon: '🔥',
      description: '升级熔炉：所有熔炉配方所需计数值减半，并可锻造钢材',
      cost: { iron_ingot: 10, coke: 12, brick: 15 },
      requires: 'unlock_iron_smelt',
      branch: 'smelting',
    },
    {
      id: 'unlock_steel_smelt',
      name: '钢材锻造',
      icon: '🔩',
      description: '解锁钢配方：2铁锭+1焦炭→1钢（需已升级熔炉）',
      cost: { iron_ingot: 8, coke: 6, brick: 8 },
      requires: 'unlock_furnace_upgrade',
      branch: 'smelting',
    },
    {
      id: 'unlock_gold_mine',
      name: '金矿',
      icon: '🟨',
      description: '解锁金矿（终极资源点，计数 130）',
      cost: { steel: 12, silver_ingot: 8, gunpowder: 6 },
      requires: 'unlock_steel_smelt',
      branch: 'mining',
    },
    {
      id: 'unlock_crystal',
      name: '水晶洞',
      icon: '💎',
      description: '解锁水晶洞（终极资源点，计数 130）',
      cost: { steel: 10, glass: 12, silver_ingot: 6 },
      requires: 'unlock_steel_smelt',
      branch: 'mining',
    },
    {
      id: 'unlock_meteor',
      name: '陨石坑',
      icon: '☄️',
      description: '解锁陨石坑（终极资源点，计数 130）',
      cost: { steel: 12, gunpowder: 8, obsidian: 10 },
      requires: 'unlock_steel_smelt',
      branch: 'mining',
    },
    {
      id: 'unlock_star_metal',
      name: '陨铁冶炼',
      icon: '🌟',
      description: '解锁陨铁：2陨石+1煤炭→1陨铁',
      cost: { meteorite: 8, coal: 8 },
      requires: 'unlock_meteor',
      branch: 'smelting',
    },
    {
      id: 'unlock_gold_smelt',
      name: '金锭冶炼',
      icon: '🥇',
      description: '解锁金锭：2金矿+1煤炭→1金锭',
      cost: { gold_ore: 8, coal: 6 },
      requires: 'unlock_gold_mine',
      branch: 'smelting',
    },
    {
      id: 'unlock_crystal_polish',
      name: '水晶抛光',
      icon: '💠',
      description: '解锁抛光水晶：1水晶+1玻璃→1抛光水晶',
      cost: { crystal: 6, glass: 12 },
      requires: 'unlock_crystal',
      branch: 'craft',
    },
    {
      id: 'unlock_auto_factory',
      name: '自动化工厂',
      icon: '🏭',
      description: '村民工作效率翻倍，解锁终极成就',
      cost: { iron_ingot: 20, gear: 15, brass: 10, steel: 5, gold_ingot: 3, polished_crystal: 2, star_metal: 2 },
      requires: 'unlock_star_metal',
      branch: 'endgame',
    },
  ],

  chestUpgradeCosts: {
    dropRate: [
      { wood: 20, stone: 10 },
      { wood: 30, stone: 15, plank: 5 },
      { wood: 45, stone: 25, plank: 10 },
      { wood: 60, stone: 35, plank: 15, copper_ore: 5 },
      { wood: 80, stone: 50, plank: 25, copper_ingot: 3 },
      { wood: 100, stone: 70, plank: 35, copper_ingot: 8 },
      { wood: 130, stone: 90, plank: 50, gear: 2 },
      { wood: 160, stone: 120, plank: 70, gear: 5, iron_ingot: 3 },
    ],
    rewardTypes: [
      { wood: 25, plank: 10 },
      { wood: 40, stone: 20, plank: 15 },
      { wood: 60, stone: 30, plank: 25, copper_ingot: 5 },
    ],
    rewardAmount: [
      { wood: 25, stone: 15 },
      { wood: 40, plank: 20, stone: 10 },
      { wood: 60, plank: 30, copper_ingot: 5 },
    ],
  },

  treasureChest: {
    baseDropRate: 0.01,
    dropRatePerLevel: 0.005,
    maxDropRate: 0.05,
    baseRewardTypesMin: 1,
    baseRewardTypesMax: 2,
    baseRewardAmountMin: 1,
    baseRewardAmountMax: 2,
  },

  /**
   * 村落防务：城门 + 来袭 + 战争（守卫从采集抽调，可徒手）
   * 游戏小时 = dayDurationMs / 24
   */
  defense: {
    introSeenKey: 'defenseIntroSeen',
    /** 首次袭击开战日（第 7 天）；预警提前 warningGameDays 天弹出 */
    firstRaidDay: 7,
    /** 袭击结束后距下次袭击：1～2 星期 */
    raidIntervalMinDays: 7,
    raidIntervalMaxDays: 14,
    minIntervalDays: 7,
    /** 预警提前天数（首次：第 5 天预警 → 第 7 天开战） */
    warningGameDays: 2,
    combatMaxGameHours: 10,
    /** 贴脸：近战打远程倍率；惊慌远程攻速倍率 */
    meleeVsRangedMult: 2,
    rangedPanicAspdMult: 0.5,
    /** 出击时每名近战可约束的敌人数 */
    meleeBindCount: 1,
    /** 被约束敌人仍砸门的残留比例 */
    boundGateLeak: 0.15,
    /** 攻城单位对门伤害倍率 */
    siegeGateMult: 2.2,
    /** 伤害：max(1, atk - def * defFactor)，再乘 (1 - 单位减伤) */
    defFactor: 0.5,
    /** 单位减伤上限 */
    maxUnitDr: 0.85,
    /** 单剑基础对近战/远程抗性 */
    swordBaseDrMelee: 0.1,
    swordBaseDrRanged: 0.08,
    /** 持盾时额外远程抗性（叠在盾减伤上） */
    shieldExtraRangedDr: 0.12,
    /** 剑+盾时攻速 = 单剑攻速 × 该系数（仍高于斧） */
    swordShieldAspdMult: 0.72,
    /** 剑+盾移速相对单剑 */
    swordShieldMoveMult: 0.65,
    /** 战场长度（单位） */
    fieldLength: 100,
    /** 城门/城墙位置 */
    wallX: 10,
    /** 敌方出生线 */
    spawnX: 92,
    /** 敌人可砸门的距离 */
    gateReach: 7,
    /**
     * move = 每游戏小时移动距离；range = 攻击距离
     * 近战整体快于远程；铠甲有 movePenalty
     */
    weapons: {
      bare: {
        1: { atk: 2, def: 0, hp: 12, aspd: 1.1, dr: 0, range: 22, range: 4 },
      },
      /** 斧：DPS≈同级剑；劣势=攻速低、无减伤、射程短于剑 */
      axe: {
        1: { atk: 11, def: 0, hp: 14, aspd: 0.65, dr: 0, move: 17, range: 4 },
        2: { atk: 17, def: 0, hp: 16, aspd: 0.7, dr: 0, move: 17, range: 4 },
        3: { atk: 22, def: 0, hp: 19, aspd: 0.75, dr: 0, move: 16, range: 4 },
        4: { atk: 29, def: 0, hp: 23, aspd: 0.8, dr: 0, move: 16, range: 4 },
      },
      /** 剑：攻速高、单剑有减伤、近战射程最长 */
      sword: {
        1: { atk: 5, def: 1, hp: 15, aspd: 1.4, dr: 0, move: 28, range: 6 },
        2: { atk: 8, def: 2, hp: 18, aspd: 1.45, dr: 0, move: 28, range: 6 },
        3: { atk: 11, def: 3, hp: 22, aspd: 1.5, dr: 0, move: 27, range: 6 },
        4: { atk: 15, def: 4, hp: 26, aspd: 1.55, dr: 0, move: 27, range: 6 },
      },
      /**
       * 盾：pairedDr/aloneDr = 对近战抗性基准
       * 持盾额外 +shieldExtraRangedDr 作为对远程抗性
       */
      shield: {
        1: { atk: 1, def: 2, hp: 3, aspd: 0.9, pairedDr: 0.4, aloneDr: 0.5, move: 26, range: 3 },
        2: { atk: 1, def: 3, hp: 4, aspd: 0.92, pairedDr: 0.48, aloneDr: 0.58, move: 26, range: 3 },
        3: { atk: 1, def: 4, hp: 5, aspd: 0.94, pairedDr: 0.55, aloneDr: 0.65, move: 25, range: 3 },
        4: { atk: 1, def: 5, hp: 6, aspd: 0.96, pairedDr: 0.62, aloneDr: 0.72, move: 25, range: 3 },
      },
      bow: {
        1: { atk: 4, def: 0, hp: 12, aspd: 1.4, dr: 0, move: 10, range: 48 },
        2: { atk: 6, def: 1, hp: 13, aspd: 1.45, dr: 0, move: 10, range: 50 },
        3: { atk: 9, def: 1, hp: 14, aspd: 1.5, dr: 0, move: 9, range: 52 },
        4: { atk: 12, def: 2, hp: 16, aspd: 1.55, dr: 0, move: 9, range: 54 },
      },
      crossbow: {
        1: { atk: 6, def: 0, hp: 12, aspd: 0.85, dr: 0, move: 9, range: 52 },
        2: { atk: 9, def: 1, hp: 13, aspd: 0.9, dr: 0, move: 9, range: 54 },
        3: { atk: 13, def: 1, hp: 15, aspd: 0.95, dr: 0, move: 8, range: 56 },
        4: { atk: 17, def: 2, hp: 17, aspd: 1.0, dr: 0, move: 8, range: 58 },
      },
      /** 铠甲：减伤+生命；movePenalty 降低移速 */
      armor: {
        1: { atk: 0, def: 1, hp: 6, aspd: 0, dr: 0.08, movePenalty: 0.12 },
        2: { atk: 0, def: 2, hp: 10, aspd: 0, dr: 0.12, movePenalty: 0.16 },
        3: { atk: 0, def: 3, hp: 14, aspd: 0, dr: 0.16, movePenalty: 0.2 },
        4: { atk: 0, def: 4, hp: 20, aspd: 0, dr: 0.2, movePenalty: 0.24 },
      },
    },
    /** 敌人默认移速/射程（可被 composition 覆盖） */
    enemyDefaults: {
      melee: { move: 14, range: 4 },
      ranged: { move: 8, range: 42 },
      siege: { move: 9, range: 5 },
    },
    gate: {
      maxLevel: 4,
      /** level 1..4 */
      levels: {
        1: {
          name: '木栅门',
          maxHp: 100,
          damageReduction: 0.25,
          repairAmount: 8,
          repairCost: { wood: 4, stone: 2 },
          upgradeCost: { plank: 15, stone: 20 },
        },
        2: {
          name: '石板门',
          maxHp: 180,
          damageReduction: 0.45,
          repairAmount: 10,
          repairCost: { stone_slab: 4, brick: 3 },
          upgradeCost: { stone_slab: 20, brick: 15, pitch: 6 },
        },
        3: {
          name: '砖铁门',
          maxHp: 280,
          damageReduction: 0.6,
          repairAmount: 12,
          repairCost: { brick: 5, iron_ingot: 2, lime: 3 },
          upgradeCost: { brick: 25, iron_ingot: 12, lime: 10 },
        },
        4: {
          name: '精钢门',
          maxHp: 420,
          damageReduction: 0.7,
          repairAmount: 14,
          repairCost: { steel: 2, stone_slab: 6, brick: 4 },
          upgradeCost: null,
        },
      },
      /** 修门村民每游戏小时贡献的修理进度（凑满 1 次 repairAmount 才扣费结算一次） */
      repairProgressPerWorkerHour: 0.35,
      manualRepairCooldownMs: 800,
    },
    /** 波次：显式 atk/def/hp/aspd */
    waves: [
      {
        id: 'scout',
        name: '斥候袭扰',
        minDay: 1,
        composition: [
          { id: 'bare', name: '流寇', role: 'melee', count: 4, atk: 3, def: 0, hp: 10, aspd: 1.0 },
          { id: 'club', name: '木棒匪', role: 'melee', count: 1, atk: 5, def: 1, hp: 14, aspd: 0.9 },
        ],
        tip: '近战射程：剑>斧>盾。持盾兵种对远程抗性更高。',
      },
      {
        id: 'raiders',
        name: '匪徒冲阵',
        minDay: 4,
        composition: [
          { id: 'bare', name: '流寇', role: 'melee', count: 6, atk: 3, def: 0, hp: 10, aspd: 1.0 },
          { id: 'club', name: '木棒匪', role: 'melee', count: 3, atk: 5, def: 1, hp: 14, aspd: 0.9 },
          { id: 'sling', name: '投石手', role: 'ranged', count: 2, atk: 4, def: 0, hp: 9, aspd: 1.1 },
        ],
        tip: '出现远程。防御令下近战不出城；出击可让近战扛压减破门伤。',
      },
      {
        id: 'warband',
        name: '爪牙战团',
        minDay: 8,
        composition: [
          { id: 'bare', name: '流寇', role: 'melee', count: 5, atk: 3, def: 0, hp: 10, aspd: 1.0 },
          { id: 'raider', name: '持刃爪牙', role: 'melee', count: 6, atk: 7, def: 2, hp: 18, aspd: 1.0 },
          { id: 'sling', name: '投石手', role: 'ranged', count: 4, atk: 4, def: 0, hp: 9, aspd: 1.1 },
          { id: 'ram', name: '破门锤手', role: 'siege', count: 1, atk: 4, def: 3, hp: 28, aspd: 0.55 },
        ],
        tip: '含攻城单位。建议多人修门，城门将破时抽人近战或改出击。',
      },
    ],
    failPenalty: {
      lootRatio: 0.2,
      lootMinKeep: 1,
      villagersLostMin: 1,
      villagersLostMax: 3,
      foodPanicExtra: 5,
      houseDowngradeChance: 0.55,
    },
  },

  pointUpgradeMeta: {
    count: { label: '采集升级', finalMaxCountRatio: 0.5 },
    cooldown: { label: '资源恢复', finalCooldownRatio: 1 / 16 },
    double: { label: '资源精炼', bonusPerLevel: 1 },
    prestigeMultiplier: 2,
    // 费用永久抬高：不随等级重置回落
    refineCostBump: { mult: 1.2, add: 5 }, // 资源精炼每升1级：采集/恢复价格 = 价格×1.2+5
    prestigeCostBump: 2,                   // 精炼重置：三项价格全部 ×2
    // 采集/恢复/精炼只花本资源；精炼重置才要加工品+异种资源
  },

  autoSpeed: {
    base: 0.1,
    perLevel: 0.1,
    maxLevel: 9,
    max: 1.0,
  },

  workerSpeedUpgrade: {
    costs: [
      { wood: 20 },
      { wood: 30, plank: 10 },
      { wood: 45, plank: 15 },
      { wood: 60, plank: 20, stone: 10 },
      { wood: 80, plank: 30, stone: 15 },
      { wood: 100, plank: 40, stone: 20, copper_ingot: 5 },
      { wood: 130, plank: 55, stone: 30, copper_ingot: 10 },
      { wood: 160, plank: 70, stone: 40, copper_ingot: 15, gear: 3 },
      { wood: 200, plank: 90, stone: 50, copper_ingot: 20, gear: 5 },
    ],
  },

  offline: {
    baseMinutes: 30,
    perLevelMinutes: 30,
    maxLevel: 15,
    maxMinutes: 480,
  },

  holdClick: {
    baseCooldown: 1000,
    minCooldown: 200,
    maxLevel: 10,
  },

  /**
   * 新手教程：可随时跳过；步骤靠操作完成或「下一步」推进
   * highlight: CSS 选择器数组；check/progress 由游戏逻辑解释
   */
  tutorial: {
    steps: [
      {
        id: 'chop_woods',
        title: '采集木头',
        text: '开局已有 3 木头。再砍满 2 次（共 5 木头即可解锁工作台）。继续点击中间森林。',
        highlight: ['#click-area'],
        progress: 'forestHarvests',
        target: 2,
        ensureStation: { type: 'point', id: 'forest' },
      },
      {
        id: 'open_starter_chest',
        title: '开启宝箱',
        text: '第二根木头时固定掉了一个宝箱。去左侧「宝箱」打开，里面是制作木斧的材料。',
        highlight: ['.station-btn[data-station-id="treasure_chest"]', '#click-area'],
        ensureStation: { type: 'point', id: 'treasure_chest' },
      },
      {
        id: 'unlock_workbench',
        title: '解锁工作台',
        text: '打开右侧「科技」，消耗 5 木头解锁「工作台」。',
        highlight: ['.tab-btn[data-tab="tech"]', '.tech-item[data-tech-id="unlock_workbench"]'],
        ensureTab: 'tech',
      },
      {
        id: 'craft_tool',
        title: '制作木斧',
        text: '工具制作已解锁。打开「工具」页，用宝箱里的木头+树脂下单制作「木斧」。',
        highlight: ['.tab-btn[data-tab="tools"]', '.craft-overview-item[data-recipe-id="craft_axe_1"]'],
        ensureTab: 'tools',
        progress: 'tool',
        target: 1,
      },
      {
        id: 'assign_forest',
        title: '分配村民',
        text: '可以给森林分配村民，他们会自动砍树。点下方工人栏的「+」派出至少 1 人。',
        highlight: ['#point-workers'],
        ensureStation: { type: 'point', id: 'forest' },
      },
      {
        id: 'food_intro',
        title: '别忘了食物',
        text: '记得采集食物！食物不够时村民会饥饿并降低效率；若连续缺粮，村民还会饿死。先去左侧「浆果丛」采集。',
        highlight: ['.station-btn[data-station-id="berry_bush"]', '#forage-list'],
        ensureStation: { type: 'point', id: 'berry_bush' },
        progress: 'berries',
        target: 3,
      },
      {
        id: 'warehouse_food',
        title: '今日口粮',
        text: '开局带了少量存粮，再加上刚采的浆果，今天的食物就够了。看看仓库里的食物数量，以及今日预计消耗。',
        highlight: ['.tab-btn[data-tab="warehouse"]', '.warehouse-item[data-res="food"]', '.warehouse-food-drain'],
        ensureTab: 'warehouse',
        requireNext: true,
      },
      {
        id: 'workers_breed',
        title: '村民繁衍',
        text: '打开「村民」页。有空余房屋、且食物足够时，可预约繁衍；村民会在晚上休息时段繁衍，次日加人。',
        highlight: ['.tab-btn[data-tab="workers"]', '#tutorial-village-breed'],
        ensureTab: 'workers',
        requireNext: true,
      },
      {
        id: 'worker_manage',
        title: '统一分配工作',
        text: '在村民页下方可以统一分配/收回工作；中心采集区下方也能就地加减工人。两种方式效果相同。',
        highlight: ['#tutorial-worker-manage', '.worker-station-list'],
        ensureTab: 'workers',
        requireNext: true,
      },
      {
        id: 'unlock_plank',
        title: '解锁木板加工',
        text: '回到「科技」，解锁「木板加工」（约需 10 木头）。有了加工能力，才能做出第一件成品。',
        highlight: ['.tab-btn[data-tab="tech"]', '.tech-item[data-tech-id="unlock_plank_craft"]'],
        ensureTab: 'tech',
      },
      {
        id: 'craft_plank',
        title: '第一件加工品',
        text: '打开「合成」页下单制作木板。下单后会跳到中间加工界面，点击做出 1 块即可。',
        highlight: ['.tab-btn[data-tab="craft"]', '.craft-overview-item[data-recipe-id="craft_plank"]'],
        ensureTab: 'craft',
        progress: 'plank',
        target: 1,
      },
      {
        id: 'craft_weapon',
        title: '制作第一件武器',
        text: '在「工具」页制作任意一件武器（如木弓、木剑）。下单后会跳到加工界面。',
        highlight: ['.tab-btn[data-tab="tools"]', '#tool-list'],
        ensureTab: 'tools',
        progress: 'weapon',
        target: 1,
      },
      {
        id: 'done',
        title: '教程完成',
        text: '你已学会采集、宝箱、工具、分配、口粮与加工。魔王爪牙还会来袭——记得多备防务。祝重建顺利！',
        highlight: [],
        requireNext: true,
        finishOnNext: true,
      },
    ],
  },
};

/** 成就表：资源囤积 / 人口 / 工具库存 */
GAME_DATA.achievements = (() => {
  const list = [];
  Object.values(GAME_DATA.resources).forEach(r => {
    list.push({
      id: `stock_${r.id}_10000`,
      name: `${r.name}囤积者`,
      description: `${r.icon} ${r.name}存量达到 10,000`,
      icon: r.icon,
      type: 'resource_stock',
      targetId: r.id,
      threshold: 10000,
    });
  });
  list.push({
    id: 'pop_1000',
    name: '千人村落',
    description: '村民总数达到 1,000',
    icon: '👥',
    type: 'population',
    threshold: 1000,
  });
  Object.values(GAME_DATA.villagerTools || {}).forEach(t => {
    list.push({
      id: `tool_${t.id}_200`,
      name: `${t.name}储备`,
      description: `${t.icon} ${t.name}库存合计达到 200`,
      icon: t.icon,
      type: 'tool_stock',
      targetId: t.id,
      threshold: 200,
    });
  });
  return list;
})();
