/** 工具/武器/护甲：制作配方 + 持工具效率 + 耐久（独立配置，改这里即可） */

/** 持工具工作效率（仅村民自动采集；手动点击不受影响） */
window.TOOL_EFFICIENCY = {
  /** 各工具等级对应效率（次/秒） */
  toolSpeedByLevel: { 1: 0.25, 2: 0.5, 3: 1.0, 4: 1.75 },
  /** 无等级映射时的兜底效率 */
  tooledSpeed: 0.25,
};

/** 工具耐久 */
window.TOOL_DURABILITY = {
  maxByLevel: { 1: 150, 2: 300, 3: 600, 4: 1200 },
  repairMinMissing: 0.01,
  repairCostRatio: 0.5,
  wearPerUserPerSecond: 0.2,
};

window.TOOL_RECIPES = [
    {
      id: 'craft_axe_1',
      name: '木斧',
      icon: '🪓',
      description: '木质斧：3木头+1木板',
      inputs: { wood: 3, plank: 1 },
      outputs: {},
      outputTools: { axe: { level: 1, amount: 1 } },
      requires: 'unlock_tool_crafting',
      baseMaxCount: 8,
      baseCooldown: 2000,
      isToolRecipe: true,
    },
    {
      id: 'craft_axe_2',
      name: '石斧',
      icon: '🪓',
      description: '石质斧：木板+石板',
      inputs: { plank: 2, stone_slab: 3 },
      outputs: {},
      outputTools: { axe: { level: 2, amount: 1 } },
      requires: 'unlock_quarry',
      baseMaxCount: 9,
      baseCooldown: 2500,
      isToolRecipe: true,
    },
    {
      id: 'craft_axe_3',
      name: '铁斧',
      icon: '🪓',
      description: '铁质斧：木板+铁锭',
      inputs: { plank: 2, iron_ingot: 2 },
      outputs: {},
      outputTools: { axe: { level: 3, amount: 1 } },
      requires: 'unlock_iron_smelt',
      baseMaxCount: 10,
      baseCooldown: 3000,
      isToolRecipe: true,
    },
    {
      id: 'craft_axe_4',
      name: '钢斧',
      icon: '🪓',
      description: '钢质斧：木板+钢',
      inputs: { plank: 2, steel: 1 },
      outputs: {},
      outputTools: { axe: { level: 4, amount: 1 } },
      requires: 'unlock_steel_smelt',
      baseMaxCount: 12,
      baseCooldown: 3500,
      isToolRecipe: true,
    },
    {
      id: 'craft_pickaxe_1',
      name: '木镐',
      icon: '⛏️',
      description: '木质镐：3木头+1木板',
      inputs: { wood: 3, plank: 1 },
      outputs: {},
      outputTools: { pickaxe: { level: 1, amount: 1 } },
      requires: 'unlock_tool_crafting',
      baseMaxCount: 8,
      baseCooldown: 2000,
      isToolRecipe: true,
    },
    {
      id: 'craft_pickaxe_2',
      name: '石镐',
      icon: '⛏️',
      description: '石质镐：木板+石板',
      inputs: { plank: 2, stone_slab: 3 },
      outputs: {},
      outputTools: { pickaxe: { level: 2, amount: 1 } },
      requires: 'unlock_quarry',
      baseMaxCount: 9,
      baseCooldown: 2500,
      isToolRecipe: true,
    },
    {
      id: 'craft_pickaxe_3',
      name: '铁镐',
      icon: '⛏️',
      description: '铁质镐：木板+铁锭',
      inputs: { plank: 2, iron_ingot: 2 },
      outputs: {},
      outputTools: { pickaxe: { level: 3, amount: 1 } },
      requires: 'unlock_iron_smelt',
      baseMaxCount: 10,
      baseCooldown: 3000,
      isToolRecipe: true,
    },
    {
      id: 'craft_pickaxe_4',
      name: '钢镐',
      icon: '⛏️',
      description: '钢质镐：木板+钢',
      inputs: { plank: 2, steel: 1 },
      outputs: {},
      outputTools: { pickaxe: { level: 4, amount: 1 } },
      requires: 'unlock_steel_smelt',
      baseMaxCount: 12,
      baseCooldown: 3500,
      isToolRecipe: true,
    },
    {
      id: 'craft_shovel_1',
      name: '木铲',
      icon: '🥄',
      description: '木质铲：2木头+1木板',
      inputs: { wood: 2, plank: 1 },
      outputs: {},
      outputTools: { shovel: { level: 1, amount: 1 } },
      requires: 'unlock_tool_crafting',
      baseMaxCount: 8,
      baseCooldown: 2000,
      isToolRecipe: true,
    },
    {
      id: 'craft_shovel_2',
      name: '石铲',
      icon: '🥄',
      description: '石质铲：木板+石板',
      inputs: { plank: 2, stone_slab: 2 },
      outputs: {},
      outputTools: { shovel: { level: 2, amount: 1 } },
      requires: 'unlock_quarry',
      baseMaxCount: 9,
      baseCooldown: 2500,
      isToolRecipe: true,
    },
    {
      id: 'craft_shovel_3',
      name: '铁铲',
      icon: '🥄',
      description: '铁质铲：木板+铁锭',
      inputs: { plank: 2, iron_ingot: 1 },
      outputs: {},
      outputTools: { shovel: { level: 3, amount: 1 } },
      requires: 'unlock_iron_smelt',
      baseMaxCount: 10,
      baseCooldown: 3000,
      isToolRecipe: true,
    },
    {
      id: 'craft_shovel_4',
      name: '钢铲',
      icon: '🥄',
      description: '钢质铲：木板+钢',
      inputs: { plank: 2, steel: 1 },
      outputs: {},
      outputTools: { shovel: { level: 4, amount: 1 } },
      requires: 'unlock_steel_smelt',
      baseMaxCount: 12,
      baseCooldown: 3500,
      isToolRecipe: true,
    },
    // —— 战争武器 ——
    {
      id: 'craft_bow_1',
      name: '木弓',
      icon: '🏹',
      description: '木弓：2木头+1木板+2树脂',
      inputs: { wood: 2, plank: 1, resin: 2 },
      outputs: {},
      outputTools: { bow: { level: 1, amount: 1 } },
      requires: 'unlock_tool_crafting',
      baseMaxCount: 8,
      baseCooldown: 2000,
      isToolRecipe: true,
    },
    {
      id: 'craft_bow_2',
      name: '石弓',
      icon: '🏹',
      description: '石弓：木板+石板+树脂',
      inputs: { plank: 2, stone_slab: 2, resin: 2 },
      outputs: {},
      outputTools: { bow: { level: 2, amount: 1 } },
      requires: 'unlock_quarry',
      baseMaxCount: 9,
      baseCooldown: 2500,
      isToolRecipe: true,
    },
    {
      id: 'craft_bow_3',
      name: '铁弓',
      icon: '🏹',
      description: '铁弓：木板+铁锭+树脂',
      inputs: { plank: 2, iron_ingot: 1, resin: 2 },
      outputs: {},
      outputTools: { bow: { level: 3, amount: 1 } },
      requires: 'unlock_iron_smelt',
      baseMaxCount: 10,
      baseCooldown: 3000,
      isToolRecipe: true,
    },
    {
      id: 'craft_bow_4',
      name: '钢弓',
      icon: '🏹',
      description: '钢弓：木板+钢+树脂',
      inputs: { plank: 2, steel: 1, resin: 1 },
      outputs: {},
      outputTools: { bow: { level: 4, amount: 1 } },
      requires: 'unlock_steel_smelt',
      baseMaxCount: 12,
      baseCooldown: 3500,
      isToolRecipe: true,
    },
    {
      id: 'craft_crossbow_1',
      name: '木弩',
      icon: '🎯',
      description: '木弩：3木头+1木板+1石头',
      inputs: { wood: 3, plank: 1, stone: 1 },
      outputs: {},
      outputTools: { crossbow: { level: 1, amount: 1 } },
      requires: 'unlock_tool_crafting',
      baseMaxCount: 8,
      baseCooldown: 2200,
      isToolRecipe: true,
    },
    {
      id: 'craft_crossbow_2',
      name: '石弩',
      icon: '🎯',
      description: '石弩：木板+石板+树脂',
      inputs: { plank: 2, stone_slab: 3, resin: 2 },
      outputs: {},
      outputTools: { crossbow: { level: 2, amount: 1 } },
      requires: 'unlock_quarry',
      baseMaxCount: 9,
      baseCooldown: 2700,
      isToolRecipe: true,
    },
    {
      id: 'craft_crossbow_3',
      name: '铁弩',
      icon: '🎯',
      description: '铁弩：木板+铁锭+齿轮',
      inputs: { plank: 2, iron_ingot: 2, gear: 1 },
      outputs: {},
      outputTools: { crossbow: { level: 3, amount: 1 } },
      requires: 'unlock_iron_smelt',
      baseMaxCount: 10,
      baseCooldown: 3200,
      isToolRecipe: true,
    },
    {
      id: 'craft_crossbow_4',
      name: '钢弩',
      icon: '🎯',
      description: '钢弩：木板+钢+齿轮',
      inputs: { plank: 2, steel: 1, gear: 1 },
      outputs: {},
      outputTools: { crossbow: { level: 4, amount: 1 } },
      requires: 'unlock_steel_smelt',
      baseMaxCount: 12,
      baseCooldown: 3600,
      isToolRecipe: true,
    },
    {
      id: 'craft_sword_1',
      name: '木剑',
      icon: '🗡️',
      description: '木剑：3木头+1木板',
      inputs: { wood: 3, plank: 1 },
      outputs: {},
      outputTools: { sword: { level: 1, amount: 1 } },
      requires: 'unlock_tool_crafting',
      baseMaxCount: 8,
      baseCooldown: 2000,
      isToolRecipe: true,
    },
    {
      id: 'craft_sword_2',
      name: '石剑',
      icon: '🗡️',
      description: '石剑：木板+石板',
      inputs: { plank: 2, stone_slab: 3 },
      outputs: {},
      outputTools: { sword: { level: 2, amount: 1 } },
      requires: 'unlock_quarry',
      baseMaxCount: 9,
      baseCooldown: 2500,
      isToolRecipe: true,
    },
    {
      id: 'craft_sword_3',
      name: '铁剑',
      icon: '🗡️',
      description: '铁剑：木板+铁锭',
      inputs: { plank: 2, iron_ingot: 2 },
      outputs: {},
      outputTools: { sword: { level: 3, amount: 1 } },
      requires: 'unlock_iron_smelt',
      baseMaxCount: 10,
      baseCooldown: 3000,
      isToolRecipe: true,
    },
    {
      id: 'craft_sword_4',
      name: '钢剑',
      icon: '🗡️',
      description: '钢剑：木板+钢',
      inputs: { plank: 2, steel: 1 },
      outputs: {},
      outputTools: { sword: { level: 4, amount: 1 } },
      requires: 'unlock_steel_smelt',
      baseMaxCount: 12,
      baseCooldown: 3500,
      isToolRecipe: true,
    },
    {
      id: 'craft_spear_1',
      name: '木矛',
      icon: '🔱',
      description: '木矛：3木头+1木板',
      inputs: { wood: 3, plank: 1 },
      outputs: {},
      outputTools: { spear: { level: 1, amount: 1 } },
      requires: 'unlock_tool_crafting',
      baseMaxCount: 8,
      baseCooldown: 2000,
      isToolRecipe: true,
    },
    {
      id: 'craft_spear_2',
      name: '石矛',
      icon: '🔱',
      description: '石矛：木板+石板',
      inputs: { plank: 2, stone_slab: 3 },
      outputs: {},
      outputTools: { spear: { level: 2, amount: 1 } },
      requires: 'unlock_quarry',
      baseMaxCount: 9,
      baseCooldown: 2500,
      isToolRecipe: true,
    },
    {
      id: 'craft_spear_3',
      name: '铁矛',
      icon: '🔱',
      description: '铁矛：木板+铁锭',
      inputs: { plank: 2, iron_ingot: 2 },
      outputs: {},
      outputTools: { spear: { level: 3, amount: 1 } },
      requires: 'unlock_iron_smelt',
      baseMaxCount: 10,
      baseCooldown: 3000,
      isToolRecipe: true,
    },
    {
      id: 'craft_spear_4',
      name: '钢矛',
      icon: '🔱',
      description: '钢矛：木板+钢',
      inputs: { plank: 2, steel: 1 },
      outputs: {},
      outputTools: { spear: { level: 4, amount: 1 } },
      requires: 'unlock_steel_smelt',
      baseMaxCount: 12,
      baseCooldown: 3500,
      isToolRecipe: true,
    },
    {
      id: 'craft_shield_1',
      name: '木盾',
      icon: '🛡️',
      description: '木盾：4木头+2木板',
      inputs: { wood: 4, plank: 2 },
      outputs: {},
      outputTools: { shield: { level: 1, amount: 1 } },
      requires: 'unlock_tool_crafting',
      baseMaxCount: 8,
      baseCooldown: 2000,
      isToolRecipe: true,
    },
    {
      id: 'craft_shield_2',
      name: '石盾',
      icon: '🛡️',
      description: '石盾：木板+石板',
      inputs: { plank: 3, stone_slab: 4 },
      outputs: {},
      outputTools: { shield: { level: 2, amount: 1 } },
      requires: 'unlock_quarry',
      baseMaxCount: 9,
      baseCooldown: 2500,
      isToolRecipe: true,
    },
    {
      id: 'craft_shield_3',
      name: '铁盾',
      icon: '🛡️',
      description: '铁盾：木板+铁锭',
      inputs: { plank: 2, iron_ingot: 2 },
      outputs: {},
      outputTools: { shield: { level: 3, amount: 1 } },
      requires: 'unlock_iron_smelt',
      baseMaxCount: 10,
      baseCooldown: 3000,
      isToolRecipe: true,
    },
    {
      id: 'craft_shield_4',
      name: '钢盾',
      icon: '🛡️',
      description: '钢盾：木板+钢',
      inputs: { plank: 2, steel: 1 },
      outputs: {},
      outputTools: { shield: { level: 4, amount: 1 } },
      requires: 'unlock_steel_smelt',
      baseMaxCount: 12,
      baseCooldown: 3500,
      isToolRecipe: true,
    },
    {
      id: 'craft_armor_1',
      name: '木甲',
      icon: '🥋',
      description: '木甲：4木头+2木板',
      inputs: { wood: 4, plank: 2 },
      outputs: {},
      outputTools: { armor: { level: 1, amount: 1 } },
      requires: 'unlock_tool_crafting',
      baseMaxCount: 8,
      baseCooldown: 2400,
      isToolRecipe: true,
    },
    {
      id: 'craft_armor_2',
      name: '石甲',
      icon: '🥋',
      description: '石甲：木板+石板',
      inputs: { plank: 3, stone_slab: 5 },
      outputs: {},
      outputTools: { armor: { level: 2, amount: 1 } },
      requires: 'unlock_quarry',
      baseMaxCount: 9,
      baseCooldown: 2800,
      isToolRecipe: true,
    },
    {
      id: 'craft_armor_3',
      name: '铁甲',
      icon: '🥋',
      description: '铁甲：木板+铁锭',
      inputs: { plank: 3, iron_ingot: 3 },
      outputs: {},
      outputTools: { armor: { level: 3, amount: 1 } },
      requires: 'unlock_iron_smelt',
      baseMaxCount: 10,
      baseCooldown: 3200,
      isToolRecipe: true,
    },
    {
      id: 'craft_armor_4',
      name: '钢甲',
      icon: '🥋',
      description: '钢甲：木板+钢',
      inputs: { plank: 3, steel: 2 },
      outputs: {},
      outputTools: { armor: { level: 4, amount: 1 } },
      requires: 'unlock_steel_smelt',
      baseMaxCount: 12,
      baseCooldown: 3600,
      isToolRecipe: true,
    }
];

if (typeof applyToolRecipes === 'function') applyToolRecipes(window.TOOL_RECIPES);
if (typeof applyToolEfficiency === 'function') applyToolEfficiency(window.TOOL_EFFICIENCY);
if (typeof applyToolDurability === 'function') applyToolDurability(window.TOOL_DURABILITY);
